### ISSUE TITLE
[Windows] Can't use sub commands from PowerShell 7

### ISSUE THREAD

**Issue by s-t-hg** [r-lib/rig#159]
Thank you for creating this useful product!

I tried rig 0.5.3 from PowerShell 7 on Windows 10, and this error is occurred.

```powershell
❯ rig.exe add release
ParserError:
Line |
   1 |  "C:\Program Files\rig\rig.exe" add release
     |                                 ~~~
     | Unexpected token 'add' in expression or statement.
```

Then I tried the same command on cmd.exe, it works.

And, `rig add --help` is working on PowerShell 7.

Edit: `rig default 4.3.0` is also not available.

**Comment by gaborcsardi** [comment]
Thanks for the report, this is indeed a bug. It is not about subcommands, but the commands that need admin rights fail. Seems like we need a newer release of gsudo, from https://github.com/gerardog/gsudo/releases

If I download the latest release, and replace the `c:\program files\rig\gsudo.exe` file with the new exe file, then it works, although only if I call gsudo explicitly:
```
gsudo rig default 4.3.0
```

Otherwise I get a different error, probably because of a difference in gsudo, and I'll need to update rig to fix this to add quoting:
```
PS C:\Users\csard> gsudo rig default 4.3.0
PS C:\Users\csard> rig default 4.3.0
C:\Program: The term 'C:\Program' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

So current workarounds are:
- use cmd.exe or powershell 5.x.
- calling gsudo explicitly:
  ```
  gsudo rig default 4.3.0
  ```
- using an administrator shell

**Comment by gaborcsardi** [comment]
You can download an installer from https://github.com/r-lib/rig/actions/runs/5122340910, download the windows artifact at the bottom, unzip it, and that installer hopefully works.

**Comment by s-t-hg** [comment]
> You can download an installer from [r-lib/rig/actions/runs/5122340910](https://github.com/r-lib/rig/actions/runs/5122340910), download the windows artifact at the bottom, unzip it, and that installer hopefully works.

It works for me, thanks!

**Comment by gaborcsardi** [comment]
OK, so this will be fixed in the next release, coming soon.
