### ISSUE TITLE
renv integrations?

### ISSUE THREAD

**Issue by edavidaja** [r-lib/rig#74]
Thank you for this tool! I think it's going to make lots of people's workflows a whole lot easier.

I mostly use `renv` to manage projects; since the `renv.lock` captures the version of R I snapshotted the library with, it would be cool if I could use rig to start RStudio with the correct version of R, and possibly with the library specified with the lockfile.

**Comment by gaborcsardi** [comment]
Yeah, `rig rstudio` could take a lock file. One difficulty is deciding what to do if that R version is not installed? On macOS you cannot install different patch versions for the same minor version (ie. R x.y.z1 and x.y.z1) together, so if different lock files request these, then it is quite painful to switch back and forth?

**Comment by gaborcsardi** [comment]
@edavidaja So what do you think rig should do if that version is not installed? What if only the minor version is the different? E.g. the project wants 4.1.2, but 4.1.2 is installed? 

Here's what I think:
- If the same exact version is installed, start that, obviously.
- If the same minor version is installed, i.e. 4.1.x for requested 4.1.y, then give a warning and use 4.1.x.
- Otherwise stop and error.

**Comment by edavidaja** [comment]
That sounds reasonable to me. The ["nearest" matching algorithm used by connect](https://docs.rstudio.com/connect/admin/r/#r-version-matching) is somewhat more permissive but I think major-minor is a sane default.

**Comment by aspeddro** [comment]
A suggestion, I don't know if it's in the scope of `rig`

- A command to install package dependencies and `R` version in `renv.locK`, similar to `npm install`.

NOTE: `npm` only manages dependencies.
